import type { Metadata } from 'next';
import { WrapByProviders } from './WrapByProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WrapByProviders>{children}</WrapByProviders>
      </body>
    </html>
  );
}
